apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowise
  namespace: flowise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flowise
  template:
    metadata:
      labels:
        app: flowise
    spec:
      containers:
        - name: flowise
          image: <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_REGION.amazonaws.com/flowise-backend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flowise-service
  namespace: flowise
spec:
  selector:
    app: flowise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
